apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-workload01-video-session
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://192.168.28.158:32100/nephio/workload01.git
    targetRevision: HEAD
    path: video-session
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ramp-demo
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
