//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppBundleReference) DeepCopyInto(out *AppBundleReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppBundleReference.
func (in *AppBundleReference) DeepCopy() *AppBundleReference {
	if in == nil {
		return nil
	}
	out := new(AppBundleReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentReference) DeepCopyInto(out *ComponentReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentReference.
func (in *ComponentReference) DeepCopy() *ComponentReference {
	if in == nil {
		return nil
	}
	out := new(ComponentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpochTimings) DeepCopyInto(out *EpochTimings) {
	*out = *in
	if in.PrepareStart != nil {
		in, out := &in.PrepareStart, &out.PrepareStart
		*out = (*in).DeepCopy()
	}
	if in.BarrierReached != nil {
		in, out := &in.BarrierReached, &out.BarrierReached
		*out = (*in).DeepCopy()
	}
	if in.CaptureStart != nil {
		in, out := &in.CaptureStart, &out.CaptureStart
		*out = (*in).DeepCopy()
	}
	if in.CaptureComplete != nil {
		in, out := &in.CaptureComplete, &out.CaptureComplete
		*out = (*in).DeepCopy()
	}
	if in.ValidateComplete != nil {
		in, out := &in.ValidateComplete, &out.ValidateComplete
		*out = (*in).DeepCopy()
	}
	if in.CommitTime != nil {
		in, out := &in.CommitTime, &out.CommitTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpochTimings.
func (in *EpochTimings) DeepCopy() *EpochTimings {
	if in == nil {
		return nil
	}
	out := new(EpochTimings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemberStatus) DeepCopyInto(out *MemberStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemberStatus.
func (in *MemberStatus) DeepCopy() *MemberStatus {
	if in == nil {
		return nil
	}
	out := new(MemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedName) DeepCopyInto(out *NamespacedName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName.
func (in *NamespacedName) DeepCopy() *NamespacedName {
	if in == nil {
		return nil
	}
	out := new(NamespacedName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadinessCheck) DeepCopyInto(out *ReadinessCheck) {
	*out = *in
	if in.LastProbeTime != nil {
		in, out := &in.LastProbeTime, &out.LastProbeTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadinessCheck.
func (in *ReadinessCheck) DeepCopy() *ReadinessCheck {
	if in == nil {
		return nil
	}
	out := new(ReadinessCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryArtifact) DeepCopyInto(out *RecoveryArtifact) {
	*out = *in
	if in.CapturedAt != nil {
		in, out := &in.CapturedAt, &out.CapturedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryArtifact.
func (in *RecoveryArtifact) DeepCopy() *RecoveryArtifact {
	if in == nil {
		return nil
	}
	out := new(RecoveryArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryContract) DeepCopyInto(out *RecoveryContract) {
	*out = *in
	out.RTO = in.RTO
	out.RPO = in.RPO
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryContract.
func (in *RecoveryContract) DeepCopy() *RecoveryContract {
	if in == nil {
		return nil
	}
	out := new(RecoveryContract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryGroup) DeepCopyInto(out *RecoveryGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryGroup.
func (in *RecoveryGroup) DeepCopy() *RecoveryGroup {
	if in == nil {
		return nil
	}
	out := new(RecoveryGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoveryGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryGroupList) DeepCopyInto(out *RecoveryGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RecoveryGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryGroupList.
func (in *RecoveryGroupList) DeepCopy() *RecoveryGroupList {
	if in == nil {
		return nil
	}
	out := new(RecoveryGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoveryGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryGroupSpec) DeepCopyInto(out *RecoveryGroupSpec) {
	*out = *in
	out.AppBundleRef = in.AppBundleRef
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]RecoveryMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.RecoveryContract = in.RecoveryContract
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryGroupSpec.
func (in *RecoveryGroupSpec) DeepCopy() *RecoveryGroupSpec {
	if in == nil {
		return nil
	}
	out := new(RecoveryGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryGroupStatus) DeepCopyInto(out *RecoveryGroupStatus) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]MemberStatus, len(*in))
		copy(*out, *in)
	}
	if in.LatestRecoveryPointTime != nil {
		in, out := &in.LatestRecoveryPointTime, &out.LatestRecoveryPointTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryGroupStatus.
func (in *RecoveryGroupStatus) DeepCopy() *RecoveryGroupStatus {
	if in == nil {
		return nil
	}
	out := new(RecoveryGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryMember) DeepCopyInto(out *RecoveryMember) {
	*out = *in
	out.ComponentRef = in.ComponentRef
	if in.SourceEndpoint != nil {
		in, out := &in.SourceEndpoint, &out.SourceEndpoint
		*out = new(RedisEndpoint)
		**out = **in
	}
	if in.ConsistencyKeys != nil {
		in, out := &in.ConsistencyKeys, &out.ConsistencyKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryMember.
func (in *RecoveryMember) DeepCopy() *RecoveryMember {
	if in == nil {
		return nil
	}
	out := new(RecoveryMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPath) DeepCopyInto(out *RecoveryPath) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPath.
func (in *RecoveryPath) DeepCopy() *RecoveryPath {
	if in == nil {
		return nil
	}
	out := new(RecoveryPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoveryPath) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPathList) DeepCopyInto(out *RecoveryPathList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RecoveryPath, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPathList.
func (in *RecoveryPathList) DeepCopy() *RecoveryPathList {
	if in == nil {
		return nil
	}
	out := new(RecoveryPathList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoveryPathList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPathSpec) DeepCopyInto(out *RecoveryPathSpec) {
	*out = *in
	in.TargetPrereqs.DeepCopyInto(&out.TargetPrereqs)
	if in.RecoveryActions != nil {
		in, out := &in.RecoveryActions, &out.RecoveryActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPathSpec.
func (in *RecoveryPathSpec) DeepCopy() *RecoveryPathSpec {
	if in == nil {
		return nil
	}
	out := new(RecoveryPathSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPathStatus) DeepCopyInto(out *RecoveryPathStatus) {
	*out = *in
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]ReadinessCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnmetMandatoryChecks != nil {
		in, out := &in.UnmetMandatoryChecks, &out.UnmetMandatoryChecks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastValidatedTime != nil {
		in, out := &in.LastValidatedTime, &out.LastValidatedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPathStatus.
func (in *RecoveryPathStatus) DeepCopy() *RecoveryPathStatus {
	if in == nil {
		return nil
	}
	out := new(RecoveryPathStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPoint) DeepCopyInto(out *RecoveryPoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPoint.
func (in *RecoveryPoint) DeepCopy() *RecoveryPoint {
	if in == nil {
		return nil
	}
	out := new(RecoveryPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoveryPoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPointList) DeepCopyInto(out *RecoveryPointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RecoveryPoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPointList.
func (in *RecoveryPointList) DeepCopy() *RecoveryPointList {
	if in == nil {
		return nil
	}
	out := new(RecoveryPointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoveryPointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPointSpec) DeepCopyInto(out *RecoveryPointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPointSpec.
func (in *RecoveryPointSpec) DeepCopy() *RecoveryPointSpec {
	if in == nil {
		return nil
	}
	out := new(RecoveryPointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPointStatus) DeepCopyInto(out *RecoveryPointStatus) {
	*out = *in
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]RecoveryArtifact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Validation = in.Validation
	in.Timings.DeepCopyInto(&out.Timings)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPointStatus.
func (in *RecoveryPointStatus) DeepCopy() *RecoveryPointStatus {
	if in == nil {
		return nil
	}
	out := new(RecoveryPointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisEndpoint) DeepCopyInto(out *RedisEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisEndpoint.
func (in *RedisEndpoint) DeepCopy() *RedisEndpoint {
	if in == nil {
		return nil
	}
	out := new(RedisEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetPrerequisites) DeepCopyInto(out *TargetPrerequisites) {
	*out = *in
	if in.StandbyEndpoint != nil {
		in, out := &in.StandbyEndpoint, &out.StandbyEndpoint
		*out = new(RedisEndpoint)
		**out = **in
	}
	if in.RestoreCapabilityDaemonSet != nil {
		in, out := &in.RestoreCapabilityDaemonSet, &out.RestoreCapabilityDaemonSet
		*out = new(NamespacedName)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetPrerequisites.
func (in *TargetPrerequisites) DeepCopy() *TargetPrerequisites {
	if in == nil {
		return nil
	}
	out := new(TargetPrerequisites)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationResult) DeepCopyInto(out *ValidationResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationResult.
func (in *ValidationResult) DeepCopy() *ValidationResult {
	if in == nil {
		return nil
	}
	out := new(ValidationResult)
	in.DeepCopyInto(out)
	return out
}
