//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationStep) DeepCopyInto(out *ActivationStep) {
	*out = *in
	out.Cost = in.Cost
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationStep.
func (in *ActivationStep) DeepCopy() *ActivationStep {
	if in == nil {
		return nil
	}
	out := new(ActivationStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppBundleReference) DeepCopyInto(out *AppBundleReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppBundleReference.
func (in *AppBundleReference) DeepCopy() *AppBundleReference {
	if in == nil {
		return nil
	}
	out := new(AppBundleReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarrierStatus) DeepCopyInto(out *BarrierStatus) {
	*out = *in
	if in.EstablishedAt != nil {
		in, out := &in.EstablishedAt, &out.EstablishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarrierStatus.
func (in *BarrierStatus) DeepCopy() *BarrierStatus {
	if in == nil {
		return nil
	}
	out := new(BarrierStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CandidateRecoveryPoint) DeepCopyInto(out *CandidateRecoveryPoint) {
	*out = *in
	in.RecoveryPointRef.DeepCopyInto(&out.RecoveryPointRef)
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.MissingPreparation != nil {
		in, out := &in.MissingPreparation, &out.MissingPreparation
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CandidateRecoveryPoint.
func (in *CandidateRecoveryPoint) DeepCopy() *CandidateRecoveryPoint {
	if in == nil {
		return nil
	}
	out := new(CandidateRecoveryPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentReference) DeepCopyInto(out *ComponentReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentReference.
func (in *ComponentReference) DeepCopy() *ComponentReference {
	if in == nil {
		return nil
	}
	out := new(ComponentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractStatus) DeepCopyInto(out *ContractStatus) {
	*out = *in
	out.RPO = in.RPO
	out.RecoveryPointAge = in.RecoveryPointAge
	out.FreshnessRemaining = in.FreshnessRemaining
	out.RTO = in.RTO
	out.EstimatedActivationLatency = in.EstimatedActivationLatency
	if in.ActivationSteps != nil {
		in, out := &in.ActivationSteps, &out.ActivationSteps
		*out = make([]ActivationStep, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractStatus.
func (in *ContractStatus) DeepCopy() *ContractStatus {
	if in == nil {
		return nil
	}
	out := new(ContractStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpochTimings) DeepCopyInto(out *EpochTimings) {
	*out = *in
	if in.PrepareStart != nil {
		in, out := &in.PrepareStart, &out.PrepareStart
		*out = (*in).DeepCopy()
	}
	if in.QuiesceStart != nil {
		in, out := &in.QuiesceStart, &out.QuiesceStart
		*out = (*in).DeepCopy()
	}
	if in.QuiesceComplete != nil {
		in, out := &in.QuiesceComplete, &out.QuiesceComplete
		*out = (*in).DeepCopy()
	}
	if in.BarrierReached != nil {
		in, out := &in.BarrierReached, &out.BarrierReached
		*out = (*in).DeepCopy()
	}
	if in.RedisSnapshotStart != nil {
		in, out := &in.RedisSnapshotStart, &out.RedisSnapshotStart
		*out = (*in).DeepCopy()
	}
	if in.RedisSnapshotComplete != nil {
		in, out := &in.RedisSnapshotComplete, &out.RedisSnapshotComplete
		*out = (*in).DeepCopy()
	}
	if in.CaptureStart != nil {
		in, out := &in.CaptureStart, &out.CaptureStart
		*out = (*in).DeepCopy()
	}
	if in.VideoCheckpointStart != nil {
		in, out := &in.VideoCheckpointStart, &out.VideoCheckpointStart
		*out = (*in).DeepCopy()
	}
	if in.VideoCheckpointComplete != nil {
		in, out := &in.VideoCheckpointComplete, &out.VideoCheckpointComplete
		*out = (*in).DeepCopy()
	}
	if in.CaptureComplete != nil {
		in, out := &in.CaptureComplete, &out.CaptureComplete
		*out = (*in).DeepCopy()
	}
	if in.ValidateComplete != nil {
		in, out := &in.ValidateComplete, &out.ValidateComplete
		*out = (*in).DeepCopy()
	}
	if in.CommitTime != nil {
		in, out := &in.CommitTime, &out.CommitTime
		*out = (*in).DeepCopy()
	}
	if in.ResumeTime != nil {
		in, out := &in.ResumeTime, &out.ResumeTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpochTimings.
func (in *EpochTimings) DeepCopy() *EpochTimings {
	if in == nil {
		return nil
	}
	out := new(EpochTimings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemberStatus) DeepCopyInto(out *MemberStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemberStatus.
func (in *MemberStatus) DeepCopy() *MemberStatus {
	if in == nil {
		return nil
	}
	out := new(MemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedName) DeepCopyInto(out *NamespacedName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName.
func (in *NamespacedName) DeepCopy() *NamespacedName {
	if in == nil {
		return nil
	}
	out := new(NamespacedName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreparedArtifact) DeepCopyInto(out *PreparedArtifact) {
	*out = *in
	if in.VerifiedAt != nil {
		in, out := &in.VerifiedAt, &out.VerifiedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreparedArtifact.
func (in *PreparedArtifact) DeepCopy() *PreparedArtifact {
	if in == nil {
		return nil
	}
	out := new(PreparedArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreparedRecoveryPoint) DeepCopyInto(out *PreparedRecoveryPoint) {
	*out = *in
	in.RecoveryPointRef.DeepCopyInto(&out.RecoveryPointRef)
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(TargetPlacement)
		(*in).DeepCopyInto(*out)
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]PreparedArtifact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreparedAt != nil {
		in, out := &in.PreparedAt, &out.PreparedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreparedRecoveryPoint.
func (in *PreparedRecoveryPoint) DeepCopy() *PreparedRecoveryPoint {
	if in == nil {
		return nil
	}
	out := new(PreparedRecoveryPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuiesceStatus) DeepCopyInto(out *QuiesceStatus) {
	*out = *in
	if in.QuiescedAt != nil {
		in, out := &in.QuiescedAt, &out.QuiescedAt
		*out = (*in).DeepCopy()
	}
	if in.ResumedAt != nil {
		in, out := &in.ResumedAt, &out.ResumedAt
		*out = (*in).DeepCopy()
	}
	if in.VerifySamples != nil {
		in, out := &in.VerifySamples, &out.VerifySamples
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuiesceStatus.
func (in *QuiesceStatus) DeepCopy() *QuiesceStatus {
	if in == nil {
		return nil
	}
	out := new(QuiesceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadinessCheck) DeepCopyInto(out *ReadinessCheck) {
	*out = *in
	if in.LastProbeTime != nil {
		in, out := &in.LastProbeTime, &out.LastProbeTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadinessCheck.
func (in *ReadinessCheck) DeepCopy() *ReadinessCheck {
	if in == nil {
		return nil
	}
	out := new(ReadinessCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryArtifact) DeepCopyInto(out *RecoveryArtifact) {
	*out = *in
	if in.CapturedAt != nil {
		in, out := &in.CapturedAt, &out.CapturedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryArtifact.
func (in *RecoveryArtifact) DeepCopy() *RecoveryArtifact {
	if in == nil {
		return nil
	}
	out := new(RecoveryArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryContract) DeepCopyInto(out *RecoveryContract) {
	*out = *in
	out.RTO = in.RTO
	out.RPO = in.RPO
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryContract.
func (in *RecoveryContract) DeepCopy() *RecoveryContract {
	if in == nil {
		return nil
	}
	out := new(RecoveryContract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryGroup) DeepCopyInto(out *RecoveryGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryGroup.
func (in *RecoveryGroup) DeepCopy() *RecoveryGroup {
	if in == nil {
		return nil
	}
	out := new(RecoveryGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoveryGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryGroupList) DeepCopyInto(out *RecoveryGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RecoveryGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryGroupList.
func (in *RecoveryGroupList) DeepCopy() *RecoveryGroupList {
	if in == nil {
		return nil
	}
	out := new(RecoveryGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoveryGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryGroupSpec) DeepCopyInto(out *RecoveryGroupSpec) {
	*out = *in
	out.AppBundleRef = in.AppBundleRef
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]RecoveryMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.RecoveryContract = in.RecoveryContract
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryGroupSpec.
func (in *RecoveryGroupSpec) DeepCopy() *RecoveryGroupSpec {
	if in == nil {
		return nil
	}
	out := new(RecoveryGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryGroupStatus) DeepCopyInto(out *RecoveryGroupStatus) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]MemberStatus, len(*in))
		copy(*out, *in)
	}
	if in.LatestRecoveryPointTime != nil {
		in, out := &in.LatestRecoveryPointTime, &out.LatestRecoveryPointTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryGroupStatus.
func (in *RecoveryGroupStatus) DeepCopy() *RecoveryGroupStatus {
	if in == nil {
		return nil
	}
	out := new(RecoveryGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryMember) DeepCopyInto(out *RecoveryMember) {
	*out = *in
	out.ComponentRef = in.ComponentRef
	if in.SourceEndpoint != nil {
		in, out := &in.SourceEndpoint, &out.SourceEndpoint
		*out = new(RedisEndpoint)
		**out = **in
	}
	if in.ConsistencyKeys != nil {
		in, out := &in.ConsistencyKeys, &out.ConsistencyKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryMember.
func (in *RecoveryMember) DeepCopy() *RecoveryMember {
	if in == nil {
		return nil
	}
	out := new(RecoveryMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPath) DeepCopyInto(out *RecoveryPath) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPath.
func (in *RecoveryPath) DeepCopy() *RecoveryPath {
	if in == nil {
		return nil
	}
	out := new(RecoveryPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoveryPath) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPathList) DeepCopyInto(out *RecoveryPathList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RecoveryPath, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPathList.
func (in *RecoveryPathList) DeepCopy() *RecoveryPathList {
	if in == nil {
		return nil
	}
	out := new(RecoveryPathList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoveryPathList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPathSpec) DeepCopyInto(out *RecoveryPathSpec) {
	*out = *in
	in.TargetPrereqs.DeepCopyInto(&out.TargetPrereqs)
	if in.RecoveryActions != nil {
		in, out := &in.RecoveryActions, &out.RecoveryActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPathSpec.
func (in *RecoveryPathSpec) DeepCopy() *RecoveryPathSpec {
	if in == nil {
		return nil
	}
	out := new(RecoveryPathSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPathStatus) DeepCopyInto(out *RecoveryPathStatus) {
	*out = *in
	if in.LatestRecoveryPoint != nil {
		in, out := &in.LatestRecoveryPoint, &out.LatestRecoveryPoint
		*out = new(RecoveryPointRef)
		(*in).DeepCopyInto(*out)
	}
	if in.CandidateRecoveryPoint != nil {
		in, out := &in.CandidateRecoveryPoint, &out.CandidateRecoveryPoint
		*out = new(CandidateRecoveryPoint)
		(*in).DeepCopyInto(*out)
	}
	if in.PreparedRecoveryPoint != nil {
		in, out := &in.PreparedRecoveryPoint, &out.PreparedRecoveryPoint
		*out = new(PreparedRecoveryPoint)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetPlacement != nil {
		in, out := &in.TargetPlacement, &out.TargetPlacement
		*out = new(TargetPlacement)
		(*in).DeepCopyInto(*out)
	}
	in.Contract.DeepCopyInto(&out.Contract)
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]ReadinessCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnmetMandatoryChecks != nil {
		in, out := &in.UnmetMandatoryChecks, &out.UnmetMandatoryChecks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastValidatedTime != nil {
		in, out := &in.LastValidatedTime, &out.LastValidatedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPathStatus.
func (in *RecoveryPathStatus) DeepCopy() *RecoveryPathStatus {
	if in == nil {
		return nil
	}
	out := new(RecoveryPathStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPoint) DeepCopyInto(out *RecoveryPoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPoint.
func (in *RecoveryPoint) DeepCopy() *RecoveryPoint {
	if in == nil {
		return nil
	}
	out := new(RecoveryPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoveryPoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPointList) DeepCopyInto(out *RecoveryPointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RecoveryPoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPointList.
func (in *RecoveryPointList) DeepCopy() *RecoveryPointList {
	if in == nil {
		return nil
	}
	out := new(RecoveryPointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoveryPointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPointRef) DeepCopyInto(out *RecoveryPointRef) {
	*out = *in
	if in.CommitTime != nil {
		in, out := &in.CommitTime, &out.CommitTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPointRef.
func (in *RecoveryPointRef) DeepCopy() *RecoveryPointRef {
	if in == nil {
		return nil
	}
	out := new(RecoveryPointRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPointSpec) DeepCopyInto(out *RecoveryPointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPointSpec.
func (in *RecoveryPointSpec) DeepCopy() *RecoveryPointSpec {
	if in == nil {
		return nil
	}
	out := new(RecoveryPointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPointStatus) DeepCopyInto(out *RecoveryPointStatus) {
	*out = *in
	in.Quiesce.DeepCopyInto(&out.Quiesce)
	in.Barrier.DeepCopyInto(&out.Barrier)
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]RecoveryArtifact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Validation.DeepCopyInto(&out.Validation)
	in.Timings.DeepCopyInto(&out.Timings)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPointStatus.
func (in *RecoveryPointStatus) DeepCopy() *RecoveryPointStatus {
	if in == nil {
		return nil
	}
	out := new(RecoveryPointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisEndpoint) DeepCopyInto(out *RedisEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisEndpoint.
func (in *RedisEndpoint) DeepCopy() *RedisEndpoint {
	if in == nil {
		return nil
	}
	out := new(RedisEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetPlacement) DeepCopyInto(out *TargetPlacement) {
	*out = *in
	if in.SelectedAt != nil {
		in, out := &in.SelectedAt, &out.SelectedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetPlacement.
func (in *TargetPlacement) DeepCopy() *TargetPlacement {
	if in == nil {
		return nil
	}
	out := new(TargetPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetPrerequisites) DeepCopyInto(out *TargetPrerequisites) {
	*out = *in
	if in.StandbyEndpoint != nil {
		in, out := &in.StandbyEndpoint, &out.StandbyEndpoint
		*out = new(RedisEndpoint)
		**out = **in
	}
	if in.RestoreCapabilityDaemonSet != nil {
		in, out := &in.RestoreCapabilityDaemonSet, &out.RestoreCapabilityDaemonSet
		*out = new(NamespacedName)
		**out = **in
	}
	if in.ActivationPlanWorkload != nil {
		in, out := &in.ActivationPlanWorkload, &out.ActivationPlanWorkload
		*out = new(WorkloadReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetPrerequisites.
func (in *TargetPrerequisites) DeepCopy() *TargetPrerequisites {
	if in == nil {
		return nil
	}
	out := new(TargetPrerequisites)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationCheck) DeepCopyInto(out *ValidationCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationCheck.
func (in *ValidationCheck) DeepCopy() *ValidationCheck {
	if in == nil {
		return nil
	}
	out := new(ValidationCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationResult) DeepCopyInto(out *ValidationResult) {
	*out = *in
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]ValidationCheck, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationResult.
func (in *ValidationResult) DeepCopy() *ValidationResult {
	if in == nil {
		return nil
	}
	out := new(ValidationResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadReference) DeepCopyInto(out *WorkloadReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadReference.
func (in *WorkloadReference) DeepCopy() *WorkloadReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadReference)
	in.DeepCopyInto(out)
	return out
}
