apiVersion: ramp.dcn.ssu.ac.kr/v1alpha1
kind: RecoveryGroup
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ramp.dcn.ssu.ac.kr/v1alpha1","kind":"RecoveryGroup","metadata":{"annotations":{},"name":"video-stream-rg","namespace":"default"},"spec":{"appBundleRef":{"cluster":"workload01","name":"video-stream-service","namespace":"ramp-demo"},"members":[{"componentRef":{"component":"redis","group":"data"},"consistencyKeys":["ramp:video:position"],"name":"redis","recoveryDriver":"redis-replication","sourceEndpoint":{"host":"192.168.28.238","port":30379}},{"componentRef":{"component":"video","group":"streaming"},"container":"video","name":"video","recoveryDriver":"container-checkpoint"}],"recoveryContract":{"rpo":"5s","rto":"60s"}}}
  creationTimestamp: "2026-09-21T09:25:52Z"
  generation: 1
  name: video-stream-rg
  namespace: default
  resourceVersion: "44810821"
  uid: 68c4fea8-04a9-46b6-ac60-3a7cd8181a0a
spec:
  appBundleRef:
    cluster: workload01
    name: video-stream-service
    namespace: ramp-demo
  members:
  - componentRef:
      component: redis
      group: data
    consistencyKeys:
    - ramp:video:position
    name: redis
    recoveryDriver: redis-replication
    sourceEndpoint:
      host: 192.168.28.238
      port: 30379
  - componentRef:
      component: video
      group: streaming
    container: video
    name: video
    recoveryDriver: container-checkpoint
  recoveryContract:
    rpo: 5s
    rto: 60s
status:
  conditions:
  - lastTransitionTime: "2026-09-21T09:26:00Z"
    message: 2 members resolved through AppBundle ramp-demo/video-stream-service
    observedGeneration: 1
    reason: AllMembersResolved
    status: "True"
    type: MembersResolved
  - lastTransitionTime: "2026-09-21T09:27:35Z"
    message: epoch 2 committed and validated
    observedGeneration: 1
    reason: Committed
    status: "True"
    type: RecoveryPointAvailable
  latestEpoch: 2
  latestRecoveryPoint: video-stream-rg-epoch-2
  latestRecoveryPointTime: "2026-09-21T09:27:22Z"
  members:
  - apiVersion: apps/v1
    driverReady: true
    kind: Deployment
    message: role=master offset=184431 replicas=1 logicalPosition=1419
    name: redis
    namespace: ramp-demo
    nodeName: workload01-md-0-4qfvd-gnqcb
    podName: redis-primary-579fc4d97c-ssqhq
    recoveryDriver: redis-replication
    resolved: true
    resourceName: redis-primary
  - apiVersion: apps/v1
    driverReady: true
    kind: Deployment
    message: checkpointable container "video" on node workload01-md-0-4qfvd-gnqcb
    name: video
    namespace: ramp-demo
    nodeName: workload01-md-0-4qfvd-gnqcb
    podName: video-session-c6b57c879-q2gbt
    recoveryDriver: container-checkpoint
    resolved: true
    resourceName: video-session
  observedGeneration: 1
  phase: Resolved
